name: YML 1 (UNO)
run-name: On ${{ github.event_name }} in ${{ github.ref }}

on: 
  workflow_dispatch:
  push:
    branches:
      - 'master'
      - 'dev'
      - 'branch1'
      - 'branch2'
  pull_request:
    branches:
      - 'master'
      - 'dev'
      - 'branch1'
      - 'branch2'
jobs:
  jobMaster:
    name: jobMaster
    if: ${{ github.ref_name }} == "master"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: |
            cat Lectura.txt
            echo "${{ github.ref_name }}"
            echo "${{ github.ref_name }} == master"

  jobDev:
    name: jobDev
    if: ${{ github.ref_name }} == "dev"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: |
            cat Lectura.txt
            echo "${{ github.ref_name }}"
            echo "${{ github.ref_name }} == dev"

  jobBranch1:
    if: ${{ github.ref_name }} == "branch1"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: |
            cat Lectura.txt
            echo "${{ github.ref_name }}"
            echo "${{ github.ref_name }} == branch1"

  jobBranch2:
    if: ${{ github.ref_name }} == "branch2"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: |
            cat Lectura.txt
            echo "${{ github.ref_name }}"
            echo "${{ github.ref_name }} == branch2"
